<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('app.decision_letter') }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; margin: 40px; }
        .header { border-bottom: 2px solid #3b82f6; padding-bottom: 15px; margin-bottom: 30px; }
        .header h1 { font-size: 18px; margin: 0; color: #1e3a5f; }
        .header p { margin: 4px 0 0; color: #6b7280; font-size: 11px; }
        .status-approved { color: #059669; font-weight: bold; font-size: 14px; }
        .status-rejected { color: #dc2626; font-weight: bold; font-size: 14px; }
        .info-table { width: 100%; margin: 20px 0; }
        .info-table td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }
        .info-table td:first-child { font-weight: bold; width: 200px; color: #374151; }
        .info-table td:last-child { color: #111827; }
        .reason { background: #fef2f2; padding: 12px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #dc2626; }
        .signature { margin-top: 60px; }
        .signature-line { border-top: 1px solid #374151; width: 250px; margin-top: 40px; padding-top: 5px; font-size: 11px; color: #6b7280; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; text-align: center; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $orgName }}</h1>
        <p>{{ __('app.decision_letter') }} - {{ now()->format('d.m.Y') }}</p>
    </div>

    <p>{{ __('app.dear') }} {{ $absence->user->name }},</p>

    <p>
        @if($absence->status === 'approved')
        <span class="status-approved">{{ __('app.request_approved_text') }}</span>
        @else
        <span class="status-rejected">{{ __('app.request_rejected_text') }}</span>
        @endif
    </p>

    <table class="info-table">
        <tr>
            <td>{{ __('app.employee_name') }}</td>
            <td>{{ $absence->user->name }}</td>
        </tr>
        <tr>
            <td>{{ __('app.absence_type') }}</td>
            <td>{{ $absence->absenceType->name ?? '-' }}</td>
        </tr>
        <tr>
            <td>{{ __('app.start_date') }}</td>
            <td>{{ $absence->start_date->format('d.m.Y') }}</td>
        </tr>
        <tr>
            <td>{{ __('app.end_date') }}</td>
            <td>{{ $absence->end_date->format('d.m.Y') }}</td>
        </tr>
        <tr>
            <td>{{ __('app.days') }}</td>
            <td>{{ $absence->total_days }}</td>
        </tr>
        <tr>
            <td>{{ __('app.status') }}</td>
            <td>{{ __('app.' . $absence->status) }}</td>
        </tr>
        <tr>
            <td>{{ __('app.decided_by') }}</td>
            <td>{{ $absence->approver->name ?? '-' }}</td>
        </tr>
        <tr>
            <td>{{ __('app.decided_on') }}</td>
            <td>{{ $absence->approved_at ? $absence->approved_at->format('d.m.Y H:i') : '-' }}</td>
        </tr>
    </table>

    @if($absence->status === 'rejected' && $absence->rejection_reason)
    <div class="reason">
        <strong>{{ __('app.rejection_reason') }}:</strong><br>
        {{ $absence->rejection_reason }}
    </div>
    @endif

    @if($absence->notes)
    <p><strong>{{ __('app.notes') }}:</strong> {{ $absence->notes }}</p>
    @endif

    <div class="signature">
        <div class="signature-line">
            {{ $absence->approver->name ?? '' }}, {{ now()->format('d.m.Y') }}
        </div>
    </div>

    <div class="footer">
        {{ $orgName }} &middot; Generated by TimeButler &middot; {{ now()->format('d.m.Y H:i') }}
    </div>
</body>
</html>
