<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('app.team_calendar') }} - {{ $monthName }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #1f2937; margin: 10px; }
        .header { border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-bottom: 15px; }
        .header h1 { font-size: 16px; margin: 0; color: #1e3a5f; }
        .header p { margin: 2px 0 0; color: #6b7280; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f3f4f6; padding: 4px 2px; text-align: center; font-size: 8px; border: 1px solid #d1d5db; }
        th.name { text-align: left; padding-left: 6px; min-width: 120px; }
        td { padding: 3px 1px; text-align: center; border: 1px solid #e5e7eb; height: 22px; }
        td.name { text-align: left; padding-left: 6px; font-weight: bold; font-size: 9px; }
        .weekend { background: #f3f4f6; }
        .holiday { background: #fee2e2; color: #dc2626; font-weight: bold; }
        .today { border: 2px solid #3b82f6; }
        .footer { margin-top: 15px; text-align: center; font-size: 8px; color: #9ca3af; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $orgName }} - {{ __('app.team_calendar') }}</h1>
        <p>{{ $monthName }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th class="name">{{ __('app.employee_name') }}</th>
                @for($d = 1; $d <= $daysInMonth; $d++)
                @php $date = $startOfMonth->copy()->addDays($d - 1); @endphp
                <th class="{{ $date->isWeekend() ? 'weekend' : '' }}">
                    {{ $date->format('D')[0] }}<br>{{ $d }}
                </th>
                @endfor
            </tr>
        </thead>
        <tbody>
            @foreach($calendarData as $row)
            <tr>
                <td class="name">{{ $row['member']->name }}</td>
                @foreach($row['days'] as $d => $dayData)
                <td class="{{ $dayData['is_weekend'] ? 'weekend' : '' }}" style="{{ $dayData['absence'] ? 'background-color: ' . ($dayData['absence']->absenceType->color ?? '#6b7280') . '; color: white; font-weight: bold;' : ($dayData['holidays'] && $dayData['holidays']->isNotEmpty() ? 'background-color: #fee2e2; color: #dc2626;' : '') }}">
                    @if($dayData['absence'])
                        {{ strtoupper(substr($dayData['absence']->absenceType->name ?? 'A', 0, 1)) }}
                    @elseif($dayData['holidays'] && $dayData['holidays']->isNotEmpty())
                        F
                    @endif
                </td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by TimeCheck &middot; {{ now()->format('d.m.Y H:i') }}
    </div>
</body>
</html>
