<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('app.absences') }} Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; }
        .header { border-bottom: 2px solid #3b82f6; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { font-size: 20px; margin: 0; color: #1e3a5f; }
        .header p { margin: 4px 0 0; color: #6b7280; font-size: 10px; }
        .summary { margin-bottom: 20px; }
        .summary-item { display: inline-block; background: #f3f4f6; padding: 8px 14px; border-radius: 6px; margin: 0 6px 6px 0; text-align: center; }
        .summary-item strong { display: block; font-size: 16px; color: #111827; }
        .summary-item span { font-size: 9px; color: #6b7280; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f9fafb; padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; color: #6b7280; border-bottom: 2px solid #e5e7eb; }
        td { padding: 7px 10px; border-bottom: 1px solid #f3f4f6; }
        tr:nth-child(even) { background: #f9fafb; }
        .status-approved { color: #059669; font-weight: bold; }
        .status-pending { color: #d97706; font-weight: bold; }
        .status-rejected { color: #dc2626; font-weight: bold; }
        .footer { margin-top: 30px; text-align: center; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $orgName }} - {{ __('app.absences') }} Report</h1>
        <p>{{ $startDate->format('d.m.Y') }} - {{ $endDate->format('d.m.Y') }}</p>
    </div>

    @if($summary->isNotEmpty())
    <div class="summary">
        @foreach($summary as $type => $data)
        <div class="summary-item">
            <strong>{{ $data['count'] }}</strong>
            <span>{{ $type }}<br>{{ $data['total_days'] }} {{ __('app.days') }}</span>
        </div>
        @endforeach
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>{{ __('app.employee_name') }}</th>
                <th>{{ __('app.absence_type') }}</th>
                <th>{{ __('app.start_date') }}</th>
                <th>{{ __('app.end_date') }}</th>
                <th>{{ __('app.days') }}</th>
                <th>{{ __('app.status') }}</th>
                <th>{{ __('app.notes') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($absences as $absence)
            <tr>
                <td>{{ $absence->user->name ?? '-' }}</td>
                <td>{{ $absence->absenceType->name ?? '-' }}</td>
                <td>{{ $absence->start_date->format('d.m.Y') }}</td>
                <td>{{ $absence->end_date->format('d.m.Y') }}</td>
                <td>{{ $absence->total_days }}</td>
                <td class="status-{{ $absence->status }}">{{ __('app.' . $absence->status) }}</td>
                <td>{{ $absence->notes ?? '' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by TimeCheck &middot; {{ now()->format('d.m.Y H:i') }}
    </div>
</body>
</html>
