<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('app.time_tracking') }} Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; }
        .header { border-bottom: 2px solid #059669; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { font-size: 20px; margin: 0; color: #064e3b; }
        .header p { margin: 4px 0 0; color: #6b7280; font-size: 10px; }
        .total { background: #f0fdf4; padding: 12px 16px; border-radius: 8px; margin-bottom: 20px; }
        .total strong { font-size: 18px; color: #059669; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f9fafb; padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; color: #6b7280; border-bottom: 2px solid #e5e7eb; }
        td { padding: 7px 10px; border-bottom: 1px solid #f3f4f6; }
        tr:nth-child(even) { background: #f9fafb; }
        .footer { margin-top: 30px; text-align: center; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $orgName }} - {{ __('app.time_tracking') }} Report</h1>
        <p>{{ $startDate->format('d.m.Y') }} - {{ $endDate->format('d.m.Y') }}</p>
    </div>

    <div class="total">
        {{ __('app.total_hours') }}: <strong>{{ intdiv($totalMinutes, 60) }}h {{ $totalMinutes % 60 }}m</strong>
    </div>

    <table>
        <thead>
            <tr>
                <th>{{ __('app.employee_name') }}</th>
                <th>{{ __('app.start_date') }}</th>
                <th>{{ __('app.start_time') }}</th>
                <th>{{ __('app.end_time') }}</th>
                <th>{{ __('app.break') }}</th>
                <th>{{ __('app.total_hours') }}</th>
                <th>{{ __('app.project') }}</th>
                <th>{{ __('app.status') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($entries as $entry)
            <tr>
                <td>{{ $entry->user->name ?? '-' }}</td>
                <td>{{ $entry->date->format('d.m.Y') }}</td>
                <td>{{ $entry->start_time ?? '-' }}</td>
                <td>{{ $entry->end_time ?? '-' }}</td>
                <td>{{ $entry->break_minutes }}m</td>
                <td><strong>{{ $entry->formatted_hours }}</strong></td>
                <td>{{ $entry->project ?? '-' }}</td>
                <td>{{ __('app.' . $entry->status) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by TimeButler &middot; {{ now()->format('d.m.Y H:i') }}
    </div>
</body>
</html>
